SUBROUTINE ibmopn (*,*,lu,fname)
     
!     THIS MDS SUBROUTINE OPENS AN IBM FORTRAN LOGICAL UNIT WHICH HAS
!     NOT BEEN ASSIGNED EXTERNALLY.
 
!     THIS SUBROUTINE USES THE FOLLOWING 3 IBM SYSTEM ROUTINES:
 
!     IQZDDN - TO DETERMINE WHETHER FILE ALREADY EXISTS OR NOT
!     QQDCBF - TO DYNAMICALLY BUILD AN ATTRIBUTE LIST BY DDNAME
!     QQGETF - TO DYNAMICALLY ALLOCATE FILE IN TSO OR BATCH
 
!     ALTERNATE RETURN 1: FILE OPENED SUCESSFULLY
!     ALTERNATE RETURN 2: ERROR OPENING FILE
 
 
 , INTENT(IN OUT)                         :: *
 , INTENT(IN OUT)                         :: *
 INTEGER, INTENT(OUT)                     :: lu
 CHARACTER (LEN=8), INTENT(OUT)           :: fname
 CHARACTER (LEN=3) :: odnw
 CHARACTER (LEN=3) :: NEW
 CHARACTER (LEN=3) :: OLD
 
 DATA       OLD, NEW / 'OLD', 'NEW' /
 
 istus = iqzddn(fname)
 odnw  = OLD
 IF (istus /= 0) GO TO 10
 odnw = NEW
 CALL qqdcbf (fname,0,'F  ',80,80,da)
 10 CALL qqgetf (lu,fname,ierr)
 IF (ierr /= 0) GO TO 20
 OPEN (UNIT=lu,FILE=fname,STATUS=odnw,ERR=20)
 RETURN 1
 
!     ERROR
 
 20 RETURN 2
END SUBROUTINE ibmopn
