SUBROUTINE cmckdf
     
!     THIS SUBROUTINE DETERMINES WHETHER ALL (TRANSFORMED) LOCAL
!     COORDINATE SYSTEMS SPECIFIED AT A GIVEN CONNECTION ARE COMPATABLE
 
 LOGICAL :: first,ferror
 INTEGER :: sccstm,scsfil,scconn,score,buf2,ecpt1,ist(7),  &
     ce(9),cstmid(7),combo,idpsub(7),nam(2),outt
 DIMENSION       ecpt(4),cstm(7,9),tt(9),iz(1)
 CHARACTER (LEN=23) :: ufm
 COMMON /xmssg / ufm
 COMMON /cmb001/ scr1,scr2,scbdat,scsfil,scconn,scmcon,sctoc,  &
     geom4,casecc,sccstm,scr3
 COMMON /cmb002/ buf1,buf2,buf3,buf4,buf5,score,lcore,intp,outt
 COMMON /cmb003/ combo(7,5),conset,iauto,toler,npsub,conect,tran,  &
     mcon,restct(7,7),isort,origin(7,3),iprint
 COMMON /zzzzzz/ z(1)
 COMMON /BLANK / step,idry
 EQUIVALENCE     (iz(1),z(1)), (ecpt1,ecpt(1))
 DATA    nam   / 4HCMCK,4HDF  /
 
 DO  i = 2,4
   ecpt(i) = 0.0
 END DO
 ferror  = .true.
 
!     READ CSTM INTO OPEN CORE
 
 ifile = sccstm
 icstm = score
 llco  = lcore
 CALL OPEN (*300,sccstm,z(buf2),0)
 CALL READ (*20,*20,sccstm,z(icstm),llco,1,nw)
 GO TO 320
 20 llco = llco - nw
 CALL CLOSE (sccstm,1)
 IF (nw == 0) GO TO 350
 CALL pretrs (z(icstm),nw)
 
!     READ ALL BGSS FILES INTO OPEN CORE
 
 ibgss = score + nw
 ifile = scsfil
 CALL OPEN (*300,scsfil,z(buf2),0)
 jj = 0
 DO  i = 1,npsub
   ist(i) = ibgss + jj
   ncsub  = combo(i,5) + 1
   DO  j = 1,ncsub
     CALL fwdrec (*310,scsfil)
   END DO
   CALL READ (*300,*40,scsfil,z(ibgss+jj),llco,1,nn)
   GO TO 320
   40 llco = llco - nn
   jj   = jj + nn + 1
   CALL skpfil (scsfil,1)
 END DO
 CALL CLOSE (scsfil,1)
 
!     BEGIN READING CONNECTION ENTRIES
 
 ifile = scconn
 CALL OPEN (*300,scconn,z(buf2),0)
 60 CALL READ (*230,*70,scconn,ce,10,1,nn)
 GO TO 320
 70 npt = 0
 DO  i = 1,npsub
   
!     CE(3)...CE(NN) ARE INTERNAL POINT NO.
   
   IF (ce(i+2) == 0) CYCLE
   npt = npt + 1
   loc = ist(i) + (ce(i+2)-1)*4
   cstmid(npt) = iz(loc)
   idpsub(npt) = i
 END DO
 
!     CHECK FOR NO CSTMS THIS ENTRY
 
 isum = 0
 DO  i = 1,npt
   isum = isum + cstmid(i)
 END DO
 IF (isum == 0) GO TO 60
 
!     GET CSTM MATRICES AND LOAD INTO CSTM ARRAY
 
 DO  i = 1,npt
   ecpt1 = cstmid(i)
   IF (ecpt1 == 0) GO TO 110
   CALL transs (ecpt,tt)
   DO  j = 1,9
     cstm(i,j) = tt(j)
   END DO
   CYCLE
   110 DO  j = 1,9
     cstm(i,j) = 0.0
   END DO
   cstm(i,1) = 1.0
   cstm(i,5) = 1.0
   cstm(i,9) = 1.0
 END DO
 
!     COMPARE EACH MATRIX AGAINST OTHERS
 
 nptm1 = npt - 1
 DO  i = 1,nptm1
   first = .true.
   j = i + 1
   DO  k  = j,npt
     DO  kk = 1,9
       IF (ABS(cstm(i,kk)-cstm(k,kk)) < 1.e-3) CYCLE
       GO TO 150
     END DO
     CYCLE
     150 IF (.NOT.ferror) GO TO 170
     ferror = .false.
     WRITE  (outt,160) ufm
     160 FORMAT (a23,' 6528, INCOMPATABLE LOCAL COORDINATE SYSTEMS HAVE ',  &
         'BEEN FOUND.', /5X,'CONNECTION OF POINTS IS IMPOSSIBLE', &
!    2        ', SUMMARY FOLLOWS.', /5X,'(LOCAL COORDINATE SYSTEMS ARE',
!    3        ' THE TRNASFORMED OVERALL STSTEM GENERATED BY COMB1,',
!    4        /5X,'SEE PROGRM. MANUAL P 4.128-7, 9TH STEP)', //,
!    5        ' *** SUGGESTION - YOUR SUBSTRUCTURING PROBLEM MAY ',
!    6        'REQUIRE THE ''GTRAN'' CARD(S) ***',/)
      '. (SUGGESTION - USE ''GTRAN'' CARD(S))', /5X,  &
         'SUMMARY IN TERMS OF THE JUST-FORMED INTERNAL DOF AND ',  &
         'INTERNAL COORD. SYSTEM ID''S PER', /5X, 'THE EQSS AND BGSS FOLLOWS.',/)
     170 IF (.NOT.first) GO TO 190
     first = .false.
     isub  = idpsub(i) + 2
     WRITE  (outt,180) cstmid(i),cstm(i,1),cstm(i,4),cstm(i,7),  &
         idpsub(i),cstm(i,2),cstm(i,5),cstm(i,8),  &
         ce(isub) ,cstm(i,3),cstm(i,6),cstm(i,9)
     180 FORMAT (/1X,76(1H*),/,' THE FOLLOWING MISMATCHED LOCAL COORDINATE'  &
         ,      ' SYSTEMS (CSTM) HAVE BEEN FOUND FOR', //,  &
         ' LOCAL COORDINATE SYSTEM ID NO.',i9,8X,3E9.2, /,  &
         ' PSEUDOSTRUCTURE ID NO.',i5,20X,3E9.2, /,  &
         ' INTERNAL POINT NO.',i9,20X,3E9.2)
     idry  = -2
     190 isub  = idpsub(k) + 2
     WRITE  (outt,200) cstmid(k),cstm(k,1),cstm(k,4),cstm(k,7),  &
         idpsub(k),cstm(k,2),cstm(k,5),cstm(k,8),  &
         ce(isub), cstm(k,3),cstm(k,6),cstm(k,9)
     200 FORMAT (/12X,'AND',7X,'LOCAL COORDINATE SYSTEM ID NO.',i9,8X,  &
         3E9.2, /22X,'PSEUDOSTRUCTURE ID NO.',i5,20X,3E9.2,  &
         /22X,'INTERNAL POINT NO.',i9,20X,3E9.2)
   END DO
 END DO
 GO TO 60
 
 230 CALL CLOSE (scconn,1)
 GO TO 350
 
 300 imsg = -1
 GO TO 330
 310 imsg = -2
 GO TO 330
 320 imsg = -8
 330 CALL mesage (imsg,ifile,nam)
 
 350 RETURN
END SUBROUTINE cmckdf
