SUBROUTINE fbs (zs,zd)
     
!     GIVEN A LOWER TRIANGULAR FACTOR WITH DIAGONAL SUPERIMPOSED, AND
!     WRITTEN WITH TRAILING STRING DEFINITION WORDS, FBS WILL PERFORM
!     THE FORWARD-BACKWARD SUBSTITUTION NECESSARY TO SOLVE A LINEAR
!     SYSTEM OF EQUATIONS.
 
!     THE ARE TWO METHODS AVAILABLE FOR THIS PROCESS.
!     METHOD 1 - THIS METHOD READS AS MANY RIGHT HAND VECTORS INTO MEMORY
!                AS POSSIBLE, AND THEN READS THE LOWER TRIANGULAR MATRIX
!                USING GETSTR AND GETSTB TO SOLVE FOR THE SOLUTION VECTORS.
!                MORE THAN ONE PASS MAY BE REQUIRED IF INSUFFICIENT MEMORY
!                EXISTS FOR LOADING ALL RIGHT HAND VECTORS AT ONE TIME.
!                THIS METHOD IS THE OLDER OF THE TWO METHODS.
!                (SEE SUBROUTINES FBSF, FBSF1, FBSF2, FBSF3 AND FBSF4)
!     METHOD 2 - THIS METHOD IS THE SAME AS METHOD 1 WITH THE EXCEPTION
!                THAT MEMORY EXISTS FOR LOADING PART OR ALL OF THE LOWER
!                TRIANGULAR MATRIX INTO OPEN CORE AFTER LOADING ALL OF
!                THE RIGHT HAND VECTORS INTO OPEN CORE.  THIS METHOD
!                WILL ELIMINATE THE NEED TO READ THE LOWER TRIANGULAR
!                MATRIX TWICE (ONCE FORWARD AND ONCE BACKWARD).
!                (SEE SUBROUTINES FBSI, FBSI1, FBSI2, FBSI3 AND FBSI4)
 
!     THE SELECTION OF METHOD 1 OR 2 IS DEPENDENT UPON WHETHER
!     MEMORY EXISTS FOR READING THE LOWER TRIANGULAR MATRIX INTO MEMORY
 
!     SEE SUBROUTINES FBSF AND FBSI FOR OPEN CORE LAYOUTS
 
 
 REAL, INTENT(IN OUT)                     :: zs(1)
 DOUBLE  PRECISION, INTENT(IN OUT)        :: zd(1)
 INTEGER :: dbl      ,dbb      ,sysbuf  &
     ,                          words    ,rlcmpx   ,rc  &
     ,                          typel    ,typeb
 
 
 COMMON /fbsx  / dbl(7)    ,dbu(7)   ,dbb(7)   ,dbx(7)   ,lcore  &
     ,               prec      ,SIGN     ,scrx
 COMMON /system/ sysbuf    ,nout
 COMMON /TYPE  / prc(2)    ,words(4) ,rlcmpx(4)
 
!     GENERAL INITIALIZATION
 
!   DIAG 46 FORCES METHOD ONE
 
 CALL sswtch ( 46, l46 )
 IF ( l46 /= 0 ) GO TO 1000
 ncol    = dbl( 2 )
 typel   = dbl( 5 )
 typeb   = dbb( 5 )
 rc      = rlcmpx( typeb )
 
!     NRHVWD = NUMBER OF WORDS REQUIRED FOR EACH RIGHT HAND VECTOR
!     NRHV   = NUMBER OF RIGHT HAND VECTORS
 
 nrhvwd    = words(typel) * ncol
 nrhv      = dbb(2)
 
! CHECK FOR RIGHT HAND VECTORS BEING THE IDENTITY MATRIX
 
 IF ( dbb( 4 ) == 8 ) nrhv = ncol
 
! COMPUTE THE MEMORY TO READ ALL OF THE RIGHT HAND VECTORS INTO MEMORY
 
 need      = nrhv * nrhvwd
 iremain   = lcore - 2 * sysbuf - need
 
! IF LESS THAN ONE COLUMN WORTH OF MEMORY AVAILABLE, USE METHOD ONE
 
 IF ( iremain >= nrhvwd ) GO TO 2000
 
!  METHOD ONE - FIRST, CHECK FOR SUFFICIENT MEMORY FOR PROCESS
 
 1000  memavl = lcore - 2*sysbuf - nrhvwd
 IF ( memavl <= 0 ) CALL mesage ( -8, -memavl, subnam )
 CALL fbsf ( zs, zd )
 GO TO 7000
 
!  METHOD TWO
 
 2000  CALL fbsi ( zs, zd )
 7000  CONTINUE
 RETURN
END SUBROUTINE fbs
