SUBROUTINE ifp1d (msno)
     
!     MESSAGE WRITER FOR IFP1
 
 
 INTEGER, INTENT(IN OUT)                  :: msno
 INTEGER :: amsno
 CHARACTER (LEN=25) :: uwm
 CHARACTER (LEN=23) :: ufm
 COMMON /xmssg / ufm,uwm
 COMMON /system/ d,nout,nogo,dd(5),nlpp,ddd(2),line
 DATA    maxmsg/ 646   /
 
 amsno = IABS(msno)
 IF (msno  < 0) nogo = 1
 IF (amsno > maxmsg) GO TO 40
 IF (amsno == 612) CALL page1
 IF (msno <= 0) WRITE (nout,10) ufm,amsno
 IF (msno > 0) WRITE (nout,20) uwm,amsno
 10 FORMAT (a23,i7)
 20 FORMAT (a25,i5)
 IF (amsno >= 634 .AND. amsno <= 644) WRITE (nout,30)
 30 FORMAT (1H+,37X,'(FROM SCAN)')
 iwher = amsno - 600
 GO TO ( 60, 80,100,120,140,160,180,200,220,240,  &
     260,280,400,420,440,460,480,500, 40, 40,  &
     40,520,540,560,580,600,620,640,660,680,  &
     700,720,740,760,780,800,820,840,860,880, 900,920,940,960,980,1000), iwher
 
!     619 - 621 ARE DEFINED IN IFP1S
 
 40 WRITE  (nout,50) amsno
 50 FORMAT (' NO TEXT AVAILABLE FOR MESSAGE',i6)
 GO TO  1100
 
 60 WRITE  (nout,70)
 70 FORMAT (' THE KEYWORD ON THE ABOVE CARD TYPE IS ILLEGAL OR MISS',  &
     'PELLED.  SEE THE FOLLOWING LIST FOR LEGAL KEYWORDS.')
 GO TO  1100
 80 WRITE  (nout,90)
 90 FORMAT (' TWO OR MORE OF THE ABOVE CARD TYPES DETECTED WHERE ',  &
     'ONLY ONE IS LEGAL.' ,/,' THE LAST FOUND WILL BE USED.')
 line = line + 1
 GO TO  1100
 100 WRITE  (nout,110)
110 FORMAT (' THE ABOVE CARD DOES NOT END PROPERLY. COMMENTS SHOULD',  &
    'BE PRECEEDED', /,' BY A DOLLAR SIGN.')
line = line + 1
GO TO  1100
120 WRITE  (nout,130)
130 FORMAT (' THE ABOVE CARD HAS A NON-INTEGER IN AN INTEGER FIELD.')
GO TO  1100
140 WRITE  (nout,150)
150 FORMAT (' A SYMSEQ OR SUBSEQ CARD APPEARS WITHOUT A SYMCOM OR ',  &
    'SUBCOM CARD.')
GO TO  1100
160 WRITE  (nout,170)
170 FORMAT (' A REQUEST FOR TEMPERATURE DEPENDENT MATERIALS OCCURS AT'  &
    ,       ' THE SUBCASE LEVEL.', /,' ONLY ONE ALLOWED PER PROBLEM.')
GO TO  1100
180 WRITE  (nout,190)
190 FORMAT (' A REPCASE CARD MUST BE PROCEEDED BY A SUBCASE CARD')
GO TO  1100
200 WRITE  (nout,210)
210 FORMAT (' THE SET ID SPECIFIED ON THE ABOVE CARD MUST BE DEFINED',  &
    ' PRIOR TO THIS CARD.')
GO TO  1100
220 WRITE  (nout,230)
230 FORMAT (' SUBCASE DELIMITER CARDS MUST HAVE A UNIQUE IDENTIFYING',  &
    ' INTEGER.')
GO TO  1100
240 WRITE  (nout,250)
250 FORMAT (' NO SET ID SPECIFIED.  ALL WILL BE ASSUMED.')
GO TO  1100
260 WRITE  (nout,270)
270 FORMAT (' TEN CARDS HAVE ILLEGAL KEY WORDS. NASTRAN ASSUMES BEGIN'  &
    ,       ' BULK CARD', /,' IS MISSING. IT WILL NOW PROCESS YOUR ',  &
    'BULK DATA.')
line = line + 1
GO TO  1100

!     THE LIST OF CASE CONTROL CARDS IS FORMATTED FOR SHORT PAPER

280 WRITE  (nout,290)
290 FORMAT (///,10(1H-),' THE FOLLOWING IS A LIST OF VALID CASE ',  &
    'CONTROL KEY WORDS EXCEPT FOR THE PLOTTER PACKAGES.',  &
    10(1H-), //6X,'KEYWORD',20X,'MEANING',/)
WRITE  (nout,300)
300 FORMAT (5X,'ACCELERATION',12X,  &
    'OUTPUT REQUEST FOR ACCELERATION VECTORS', /6X,'AEROFORCE',15X,  &
    'OUTPUT REQUEST FOR AERODYNAMIC FORCES', /6X,'AXISYMMETRIC',12X,  &
    'AXISYMMETRIC CASE SELECTION (SINE OR COSINE)', /6X,'B2PP',20X,  &
    'SELECTION OF STRUCTURAL DAMPING OR THERMAL CAPACITANCE ', 'MATRICES',  &
    /6X,'CMETHOD',17X, 'COMPLEX EIGENVALUE METHOD SELECTION',  &
    /6X,'DEFORM',18X, 'REQUEST FOR ENFORCED ELEMENT DEFORMATION',  &
    /6X,'DISPLACEMENT',12X, 'OUTPUT REQUEST FOR DISPLACEMENT VECTORS',  &
    /6X,'DLOAD',19X, 'DYNAMIC LOAD SELECTION')
WRITE  (nout,310)
310 FORMAT (6X,'DSCOEFFICIENT',11X,  &
    'DIFFERENTIAL STIFFNESS COEFFICIENT SET SELECTION', /6X,'ECHO',20X,  &
    'BULK DATA ECHO SELECTOR (SORT,UNSORT,BOTH,NONE,PUNCH)', /6X,'ELFORCE',17X,  &
    'OUTPUT REQUEST FOR ELEMENT FORCES', /6X,'ELSTRESS',16X,  &
    'OUTPUT REQUEST FOR ELEMENT STRESSES', /6X,'ESE',21X,  &
    'REQUEST FOR ELEMENT STRAIN ENERGY OUTPUT', /6X,'FMETHOD',17X,  &
    'REQUEST FOR AEROELASTIC FLUTTER METHOD', /6X,'FORCE',18X,  &
    'OUTPUT REQUEST FOR ELEMENT FORCES', /6X,'FREQUENCY',15X,  &
    'FREQUENCY SET SELECTION')
WRITE  (nout,320)
320 FORMAT (6X,'GPFORCE',17X,  &
    'REQUEST FOR GRID POINT FORCE BALANCE OUTPUT', /6X,'GUST',20X,  &
    'AEROELASTIC RESPONSE ANALYSIS INPUT LOADING CONDITION',  &
    /6X,'HARMONICS',15X,  &
    'HARMONICS TO BE PRINTED FOR AXISYMMETRIC SHELL PROBLEM', /6X,'IC',22X,  &
    'INITIAL CONDITIONS FOR DIRECT TRANSIENT PROBLEM', /6X,'K2PP',20X,  &
    'SELECTION OF STRUCT-L STIFFNESS OR THERMAL CONDUCTANCE ', 'MATRICES',  &
    /6X,'LABEL',19X, 'DEFINES PRINTER, PLOTTER AND PUNCH OUTPUT LABEL',  &
    /6X,'LINE',20X, 'NUMBER OF LINES PER PAGE (DFLT = 50 -CDC,IBM, 45 -UNIVAC)'  &
    ,      /6X,'LOAD',20X,  &
    'STATIC ANALYSIS EXTERNAL LOAD SELECTION OR HEAT POWER/', 'FLUX')
WRITE  (nout,330)
330 FORMAT (6X,'M2PP',20X,  &
    'SELECTION OF INPUT MASS MATRICES VIA DMIG CARDS', /6X,'MAXLINES',16X,  &
    'MAXIMUM NUMBER OF PRINTER LINES (DEFAULT = 20000)', /6X,'METHOD',18X,  &
    'REAL EIGENVALUE METHOD SELECTION', /6X,'MODES',19X,  &
    'DUPLICATE CASE CONTROL THIS MANY TIMES', /6X,'MPC',21X,  &
    'SELECTS MULTI-POINT CONSTRAINTS OR HEAT TRANSFER ', 'BOUNDARY TEMPS',  &
    /6X,'MPCFORCE',16X, 'OUTPUT REQUEST FOR MULTI-POINT FORCES OF CONSTRAINT',  &
    /6X,'NCHECK',18X, 'OUTPUT REQUEST FOR FORCE AND STRESS PRECISION',  &
    /6X,'NLLOAD',18X, 'OUTPUT REQUEST FOR NON-LINEAR LOADS FOR ANALYSIS SET')

CALL page1
WRITE  (nout,340)
340 FORMAT (//6X,7HKEYWORD,20X,7HMEANING, //6X,'NONLINEAR',15X,  &
    'NON-LINEAR LOAD SET FOR TRANSIENT PROBLEMS', /6X,'OFREQUENCY',14X,  &
    'SELECTS OUTPUT FREQUENCIES OR -IM- PART OF COMPLEX ', 'EIGENVALUES',  &
    /6X,'OLOAD',19X, 'OUTPUT REQUEST FOR APPLIED LOAD',  &
    /6X,'OTIME',19X, 'REQUEST FOR SELECTED OUTPUT TIMES',  &
    /6X,'OUTPUT',18X, 'OUTPUT PACKET DELIMITER (THIS CARD IS OPTIONAL)',  &
    /6X,'OUTPUT(PLOT)',12X, 'STRUCTURE PLOTTER OUTPUT PACKET DELIMITER',  &
    /6X,'OUTPUT(XYOUT)',11X,  &
    'XY OUTPUT PACKET DELIMITER (PLOTTER, PRINTER AND PUNCH)',  &
    /6X,'OUTPUT(XYPLOT)',10X, 'EQUIVALENT TO OUTPUT(XYOUT)')
WRITE  (nout,350)
350 FORMAT (6X,'PLCOEFFICIENT',11X,  &
    'PIECEWISE LINEAR COEFFICIENT SET SELECTION', /6X,'PLOTID',18X,  &
    'DEFINES PLOTTER OUTPUT HEADER FRAME TITLE', /6X,'PRESSURE',16X,  &
    'OUTPUT REQUEST FOR HYDROELASTIC PRESSURE', /6X,'RANDOM',18X,  &
    'RANDOM ANALYSIS PSDL AND RANDT SET SELECTION', /6X,'REPCASE',17X,  &
    'REPEAT THE PRECEDING CASE AGAIN', /6X,'SACCELERATION',11X,  &
    'OUTPUT REQUEST FOR SOLUTION SET ACCELERATION VECTORS', /6X,'SCAN',20X,  &
    'SCAN AND OUTPUT STRESSES OR FORCES FOR PREDETERMINED ', 'CRITERIA',  &
    /6X,'SDAMPING',16X,  &
    'MODAL FORMULATION STRUCTURAL DAMPING TABULAR FUNCTION ', 'SELECTION',  &
    /6X,'SDISPLACEMENT',11X,  &
    'OUTPUT REQUEST FOR SOLUTION SET DISPLACEMENT VECTORS')
WRITE  (nout,360)
360 FORMAT (6X,'SET',21X, 'DEFINES OUTPUT SET LIST',  &
    /6X,'SPC',21X, 'SELECTS SINGLE POINT CONSTRAINTS OR HEAT TRANSFER ',  &
    'BOUNDARY TEMP', /6X,'SPCFORCE',16X,  &
    'REQUESTS SINGLE POINT CONSTRAINT FORCES OR THERMAL POWER',  &
    /6X,'STRAIN',18X, 'OUTPUT REQUEST FOR ELEMENT STRAINS',  &
    /6X,'STRESS',18X, 'OUTPUT REQUEST FOR ELEMENT STRESSES',  &
    /6X,'SUBCASE',17X, 'SUBCASE DELIMITER',  &
    /6X,'SUBCOM',18X, 'THIS CASE IS A LINEAR COMBINATION OF THE PRECEDING ',  &
    'SUBCASES', /6X,'SUBSEQ',18X,  &
    'DEFINES COEFFICIENTS FOR LINEAR SUBCASE COMBINATION')
WRITE  (nout,370)
370 FORMAT (6X,'SUBTITLE',16X,  &
    'DEFINES PRINTER, PLOTTER AND PUNCH OUTPUT SUBTITLE', /6X,'SVECTOR',17X,  &
    'OUTPUT REQUEST FOR SOLUTION SET DISPLACEMENT VECTORS',  &
    /6X,'SVELOCITY',15X, 'OUTPUT REQUEST FOR SOLUTION SET VELOCITY VECTORS',  &
    /6X,'SYM',21X, 'SYMMETRY SUBCASE DELIMITER',  &
    /6X,'SYMCOM',18X,  &
    'THIS CASE IS A LINEAR COMBINATION OF THE PRECEDING SYM ', 'CASES',  &
    /6X,'SYMSEQ',18X,  &
    'DEFINES COEFFICIENTS FOR LINEAR SYM COMBINATION (DEFAULT', ' = 1.0)',  &
    /6X,'TEMPERATURE(BOTH)',7X,  &
    'THERMAL SET SELECTION FOR BOTH LOAD AND MATERIAL DATA',  &
    /6X,'TEMPERATURE(LOAD)',7X, 'THERMAL LOAD TEMPERATURE SET SELECTION')

CALL page1
WRITE  (nout,380)
380 FORMAT (//6X,'KEYWORD',20X,'MEANING', /6X,'TEMPERATURE(MATERIAL)',3X,  &
    'SELECTS THERMAL DEPENDENT MATERIALS OR TEMPERATURE ', 'ESTIMATES',  &
    /6X,'TFL',21X, 'TRANSFER FUNCTION SET SELECTION',  &
    /6X,'THERMAL',17X,  &
    'OUTPUT REQUEST FOR TEMPERATURES IN HEAT TRANSFER ANALYSIS'  &
    ,      /6X,'TITLE',19X, 'DEFINES PRINTER, PLOTTER AND PUNCH OUTPUT TITLE',  &
    /6X,'TSTEP',19X, 'TIME STEP SET SELECTION FOR TRANSIENT PROBLEMS',  &
    /6X,'VECTOR',18X, 'OUTPUT REQUEST FOR DISPLACEMENT VECTORS',  &
    /6X,'VELOCITY',16X, 'OUTPUT REQUEST FOR VELOCITY VECTORS',  &
    /6X,'BEGIN BULK',14X, 'THIS CARD MARKS THE END OF THE CASE CONTROL DECK')
GO TO 1110

400 WRITE  (nout,410)
410 FORMAT (' THE ABOVE SET CONTAINS -EXCEPT- WHICH IS NOT PRECEDED ',  &
    'BY -THRU-.')
GO TO  1100
420 WRITE  (nout,430)
430 FORMAT (' THE ABOVE SET IS INCORRECTLY SPECIFIED.  CHECK FORMAT ',  &
    'ON THIS OR PREVIOUS CARD.')
GO TO  1100
440 WRITE  (nout,450)
450 FORMAT (' AN IMPROPER OR NO NAME GIVEN TO THE ABOVE SET.')
GO TO  1100
460 WRITE  (nout,470)
470 FORMAT (' ELEMENT IN THRU RANGE LIES IN RANGE OF PREVIOUS THRU ',  &
    'OR EXCEPT.  MISSING ELEMENT OR INCORRECT USE OF THRU.')
GO TO  1100
480 WRITE  (nout,490)
490 FORMAT (' INCORRECT OR MISSING VALUE ON CASE CONTROL CARD. ',  &
    ' CHECK FOR CORRECT CARD FORMAT.')
GO TO  1100
500 WRITE  (nout,510)
510 FORMAT (' PLOT OUTPUT IS REQUESTED BUT THE PROPER PLOT TAPE IS ',  &
    'NOT A PHYSICAL TAPE')
GO TO  1100

520 WRITE  (nout,530)
530 FORMAT (' REAL VALUES NOT ALLOWED IN A THRU SEQUENCE.')
GO TO  1100
540 WRITE  (nout,550)
550 FORMAT (' UNEXPECTED END-OF-RECORD ON CASE CONTROL CARD.  CHECK ',  &
    'FOR CORRECT CARD FORMAT.')
GO TO  1100
560 WRITE  (nout,570)
570 FORMAT (' BEGIN BULK CARD NOT FOUND.')
GO TO  1100
580 WRITE  (nout,590)
590 FORMAT (' TOO LARGE ID ON PRECEDING SUBCASE TYPE CARD. ALL ID-S ',  &
    'MUST BE LESS THAN 99,999,999.')
GO TO  1100
600 WRITE  (nout,610)
610 FORMAT (' VALUES IN EXCEPT MUST BE SPECIFIED IN ASCENDING ORDER')
GO TO  1100
620 WRITE  (nout,630)
630 FORMAT (' THE ABOVE SUBCASE HAS BOTH A STATIC LOAD AND A REAL ',  &
    'EIGENVALUE METHOD SELECTION - REMOVE ONE.')
GO TO  1100
640 WRITE  (nout,650)
650 FORMAT (/,' THERMAL, DEFORMATION, AND EXTERNAL LOADS CANNOT HAVE',  &
    ' THE SAME SET IDENTIFICATION NUMBER.')
GO TO  1100
660 WRITE  (nout,670)
670 FORMAT (' ECHO CARD HAS REPEATED OR UNRECOGNIZABLE SPECIFICATION',  &
    ' DATA - ',/11X,'REPEATED SPECIFICATIONS WILL BE IGNORED',  &
    /11X,'UNRECOGNIZABLE SPECIFICATIONS WILL BE TREATED AS ', 'SORT.')
line = line + 2
GO TO  1100
680 WRITE  (nout,690)
690 FORMAT (' ECHO CARD WITH -NONE- SPECIFICATION HAS ADDITIONAL ',  &
    'SPECIFICATIONS WHICH WILL BE IGNORED.')
GO TO  1100
700 WRITE  (nout,710)
710 FORMAT (' PLOT AND/OR SET COMMAND CARD MISSING FROM STRUCTURE ',  &
    'PLOTTER OUTPUT PACKAGE.')
GO TO  1100
720 WRITE  (nout,730)
730 FORMAT (' XYPLOT COMMAND CARDS FOUND IN STRUCTURE PLOTTER OUTPUT',  &
    ' PACKAGE.')
GO TO  1100
740 WRITE  (nout,750)
750 FORMAT (' SUBCASE LIMIT OF 360 EXCEEDED')
GO TO  1100

!     MESSAGES 634 - 644 (760 THRU 960) ARE CALLED ONLY BY SCAN

760 WRITE  (nout,770)
770 FORMAT (5X,'KEYWORD INSIDE BRACKETS IS ILLEGAL OR MIS-SPELLED')
GO TO  1100
780 WRITE  (nout,790)
790 FORMAT (5X,'ONLY ONE SET-ID ALLOWED')
GO TO  1100
800 WRITE  (nout,810)
810 FORMAT (5X,'EXTRA VALUE ENCOUNTERED OR WRONG TYPE OF INPUT DATA')
GO TO  1100
820 WRITE  (nout,830)
830 FORMAT (5X,'ILLEGAL COMPONENT SPECIFIED')
GO TO  1100
840 WRITE  (nout,850)
850 FORMAT (5X,'COMPONENT LIMIT OF 31 IS EXCEEDED')
GO TO  1100
860 WRITE  (nout,870)
870 FORMAT (5X,'SET ID ERROR (REQUESTED BEFORE EQUAL SIGN OR ',  &
    'SPLITTED ID)')
GO TO  1100
880 WRITE  (nout,890)
890 FORMAT (5X,'TOO MANY COMPONENTS')
GO TO  1100
900 WRITE  (nout,910)
910 FORMAT (5X,'MINUS MAX EXCEEDS PLUS MAX')
GO TO  1100
920 WRITE  (nout,930)
930 FORMAT (5X,'COMPONENT NAME NOT AVAILABLE FOR ELEMENT SELECTED')
GO TO  1100
940 WRITE  (nout,950)
950 FORMAT (5X,'OUTPUT SCAN BY FORCE OR BY STRESS ONLY')
GO TO  1100
960 WRITE  (nout,970)
970 FORMAT (5X,'LARGE TOPN VALUE REQUESTED MAY RESULT IN INSUFFICIENT'  &
    ,      ' CORE IN OUTPUT SCAN MODULE LATER')
GO TO  1100

980 WRITE  (nout,990)
990 FORMAT (5X,'SORT2 REQUEST FOR STRESSES ON THE LAYERED ELEMENTS ',  &
    'IS CURRENTLY NOT SET UP BY THE RIGID FORMAT')
GO TO  1100
1000 WRITE  (nout,1010)
1010 FORMAT (5X,'LAYER OPTION IS AVAILABLE ONLY IN STRESS OR ELSTRESS')
1100 line = line + 3
IF (line >= nlpp) CALL page
1110 RETURN
END SUBROUTINE ifp1d
