SUBROUTINE mxcids(*,z,mset,msze,nwds,uset,nstrt,snam)
!-----
!   THIS SUBROUTINE CREATES A LIST OF SUBSTRUCTURE NAMES AT Z(1)
! AND AN ARRAY AT Z(NSTRT) OF LENGTH MSZE*NWDS WITH THE FIRST TWO WORDS
! OF EACH ENTRY AS,
!     1 - EXTERNAL ID * 10 + COMPONENT
!     2 - POINTER TO FIRST WORD OF SUBSTRUCTURE NAME...
 
! INPUT
!     Z     = OPEN CORE - Z(1) TO Z(NSTRT-1)
!     MSET  = ONE WORD BCD IDENTIFING SET
!     MSZE  = NUMBER OF COLUMNS IN MATRIX
!     NWDS  = NUMBER WORDS/ENTRY DESIRED (2 MINIMUM)
!     USET  = USET GINO FILE NAME
!     NSTRT = LOCATION OF FIRST OF FOUR (4) BUFFERS.
!     SNAM  = SUBSTRUCTURE NAME BEING SOLVED (2 WORD BCD).
! OUTPUT
!     *     = TASK NOT COMPLETED
!     Z     = SUBSTRUCTURE NAMES + COLUMN IDENTIFIERS (SEE ABOVE)
!     NSTRT = FIRST WORD OF COLUMN IDENTIFIERS
!-----
 
!       N O T   C O D E D   Y E T
 
 IF (mset == 1) RETURN
 RETURN 1
END SUBROUTINE mxcids
