SUBROUTINE olplot
     
!     DRIVER FOR USER SUPPLIED INTERACTIVE PLOTTER
 
!     NOTE - ALL FORTRAN STOPS MUST BE CHANGED TO RETURNS
!     OTHERWISE THE FORTRAN STOPS WILL KILL THE INTERACTIVE SESSION.
 
 INTEGER :: plt2
 COMMON /system/ ibuf,nout
 DATA plt2/13/
 
 WRITE (nout,10)
 10 FORMAT ('    USER MUST SUPPLY SITE DEPENDENT PLOTTING PACKAGE',  &
     /4X, 'IN SUBROUTINE OLPLOT FOR INTERACTIVE PLOTS')
 
 
 REWIND plt2
!     CALL THE SITE DEPENDENT PLOTTING ROUTINES HERE.
!     CALL NASPLOT
 RETURN
END SUBROUTINE olplot
