SUBROUTINE pla4
!*****
! THIS FUNCTIONAL MODULE IS THE LAST OF FOUR FUNCTIONAL MODULES UNIQUE
! TO THE PIECE-WISE LINEAR ANALYSIS (DISPLACEMENT METHOD) RIGID FORMAT.
!*****
! DMAP CALL...
 
! PLA4   CSTM,MPT,ECPTNL,GPCT,DIT,DELTAUGV/KGGNL,ECPTNL1/V,N,PLACOUNT/V,
!        N,PLSETNO/V,N,PLFACT/ $
 
! THE OUTPUT DATA BLOCKS AND PARAMETERS ARE DEFINED AS FOLLOWS...
 
! KGGNL IS THE STIFFNESS MATRIX OF NON-LINEAR (STRESS DEPENDENT)
!       ELEMENTS.
! ECPTNL1 IS THE UP-TO-DATE VERSION OF THE INPUT DATA BLOCK, ECPTNL.
!         THAT IS, THE ECPTNL1 DATA BLOCK CONTAINS THE SAME INFORMATION
!         AS ECPTNL EXCEPT THE STRESS INFORMATION IS UPDATED.
 
! PARAMETER NAMES BELOW ARE FORTRAN RATHER THAN DMAP NAMES
 
! PLACNT IS PIECE-WISE LINEAR ANALYSIS RIGID FORMAT DMAP LOOP COUNTER.
! PLSETN IS THE PLFACT CARD SET NUMBER CHOSEN BY THE USER IN HIS CASE
!        CONTROL PACKAGE.
! PLFACT IS THE FACTOR BY WHICH THE LOAD VECTOR WILL MULTIPLIED THE NEXT
!        TIME THROUGH THE PLA DMAP LOOP
!*****
! THIS ROUTINE IS THE MODULE DRIVER.  PLA41 APPENDS DISPLACEMENT INFOR-
! MATION TO THE ECPTNL DATA BLOCK AND A SCRATCH DATA BLOCK, ECPTS, OF
! THIS MERGED INFORMATION IS CREATED.  SUBROUTINE PLA42 USES THE DATA
! BLOCK ECPTS TO CREATE THE KGGNL MATRIX.  ALSO THE UPDATED ECPT INFOR-
! MATION IS OUTPUT AS DATA BLOCK ECPTNL1 BY PLA42.
!*****
 CALL pla41
 CALL pla42
 RETURN
END SUBROUTINE pla4
