SUBROUTINE setfnd(*,set,lset,id,next)
!*****
!  FINDS AN ID IN A SORTED SET LIST WHICH MAY HAVE THE NASTRAN THROUGH
!  NOTATION.  IE.  6,-18 IMPLIES 6 THRU 18.
 
!  -SET- IS THE LIST OF IDS.
!  -LSET- IS THE LENGTH OF THE LIST IN -SET-.
!  -ID- IS THE ID BEING LOOKED FOR IN THE LIST -SET-.
!  -NEXT- IS A RELATIVE INDEX INTO THE LIST -SET-.  IT SHOULD BE SET
!  TO 1 ON THE FIRST CALL TO THIS ROUTINE FOR A GIVEN LIST AND THEN
!  RETURNED ON FUTURE CALLS.
 
!  THIS ROUTINE MOVES FORWARD ONLY UNTIL AN ID IN THE LIST IS GREATER
!  THAN THE ID BEING ASKED FOR.    -NEXT-  IF NOT RESET TO 1 WILL ALLOW
!  THE ROUTINE TO SEARCH ONLY FROM WHERE LAST SEARCH LEFT OFF.
 
!  THE NON-STANDARD RETURN IS TAKEN IN THE EVENT THE ID IS NOT IN THE
!  LIST.  A NORMAL RETURN IS TAKEN IF THE ID IS IN THE LIST.
 
!  -NEXT- SHOULD BE SET TO 1 ON THE FIRST CALL TO THIS ROUTINE OR WHEN
!  AN ID TO BE LOOKED FOR IS SMALLER THAN AN ID PREVIOUSLY LOOKED FOR.
 
!  IF IDS TO BE LOOKED FOR ARE NOT IN SORT AND THE SET LIST IS IN SORT
!  WITHOUT THE NASTRAN THROUGH NOTATION, THEN THE NASTRAN BINARY SEARCH
!  ROUTINE -BISRCH- SHOULD BE USED.
 
!  IT IS OK TO CALL THIS ROUTINE WITH MORE THAN ONE OF THE SAME IDS
!  WITHOUT RESETTING -NEXT-.
!*****

 INTEGER, INTENT(IN)                      :: set(lset)
 INTEGER, INTENT(IN OUT)                  :: lset
 INTEGER, INTENT(IN OUT)                  :: id
 INTEGER, INTENT(OUT)                     :: next
 
 
 10 id1 = set(next)
 20 IF( next - lset  < 0) THEN
   GO TO    30
 ELSE IF ( next - lset  == 0) THEN
   GO TO    80
 ELSE
   GO TO   100
 END IF
 
!     STILL POSITIONED WITHIN THE SET LIST.
 
 30 IF( id - id1  < 0) THEN
   GO TO   100
 ELSE IF ( id - id1  == 0) THEN
   GO TO   110
 END IF
 
!     CHECK FOR THRU CASE
 
 40 id1 = set(next+1)
 IF( id1  < 0) THEN
   GO TO    50
 ELSE
   GO TO    70
 END IF
 
!     YES POSITIONED IN A THRU CASE
 
 50 IF( id + id1  > 0) THEN
   GO TO    60
 ELSE
   GO TO   110
 END IF
 
!     ID BEING LOOKED FOR IS BEYOND THIS THRU CASE.
 
 60 next = next + 2
 GO TO 10
 
!     NOT IN A THRU CASE
 
 70 next = next + 1
 GO TO 20
 
!     AT THE LAST ID IN THE LIST
 
 80 IF( id - id1  < 0) THEN
   GO TO   100
 ELSE IF ( id - id1  == 0) THEN
   GO TO   110
 END IF
 90 next = next + 1
 100 RETURN 1
 110 RETURN
END SUBROUTINE setfnd
