SUBROUTINE xdcode
     
!     (MACHINE INDEPENDENT FORTRAN 77 ROUTINE)
 
!     XDCODE DECODES A 20A4 ARRAY IN RECORD INTO A 80A1 ARRAY IN ICHAR
 
!     XDCODE IS CALLED ONLY BY XRGDCF, XRGDTB, XRGSST, AND XRGSUB
 
 CHARACTER (LEN=80) :: temp
 CHARACTER (LEN=8) :: temp8
 COMMON /system/ ibuf,    nout,  dm37(37),nbpw
 COMMON /xrgdxx/ skip1(3),icol,  skip2(8),record(20),ICHAR(80),  &
     skip3(2),icount,skip4(2),NAME(2)
 DATA    iblank/ 4H      /
 
 WRITE (temp,10) record
 READ  (temp,20) ICHAR
 10   FORMAT (20A4)
 20   FORMAT (80A1)
 RETURN
 
 ENTRY xecode
!     ============
 
!     XECODE ENCODES A 8A1 BCD ARRAY IN ICHAR INTO A 2A4 BCD ARRAY
!     IN NAME
!     (THIS ENTRY REPLACES THE OLD MACHINE DEPENDENT ROUTINE OF THE
!     SAME NAME)
 
!     THE INCOMING WORD IN CDC MACHINE WOULD BE ZERO FILLED, SUCH AS
!     THE CARD TABLE AND THE MED TABLE IN XGPI RESTART PROCESSING.
!     MAKE SURE THAT THE INCOMING WORD FROM A 60- OR 64- BIT MACHINE
!     IS BLANK FILLED IF IT IS LESS THAN 8 BYTE LONG
 
!     XECODE IS CALL ONLY BY XRGDTB
 
 IF (nbpw < 60 .OR. icount == 8) GO TO 25
 DO  k = icount,7
   ICHAR(icol+k) = iblank
 END DO
 25   CALL na12a8 (*50,ICHAR(icol),8,NAME,notuse)
 IF (nbpw /= 60) RETURN
 
!     BLANK OUT 2ND WORD (CDC ONLY)
 
 WRITE (temp8,30) NAME(1)
 NAME(1) = iblank
 NAME(2) = iblank
 READ (temp8,40) NAME
 30   FORMAT (a8)
 40   FORMAT (2A4)
 RETURN
 
 50   WRITE  (nout,60)
 60   FORMAT ('0BAD DATA/XECODE')
 RETURN
END SUBROUTINE xdcode
