SUBROUTINE xgpidd
     
!     THIS SUBROUTINE DEFINES ALL NAMED COMMON FOR SUBROUTINES
!     XGPI,XOSGEN,XLNKHD,XIOFL,XPARAM,XSCNDM,XFLORD,XFLDEF AND XGPIDG.
!     **NOTE - THIS PROGRAM MUST BE LOADED BEFORE ANY OF THE ABOVE.
 
 INTEGER :: bcdcnt,cpntry,diag4,diag14,diag17,diag25,dmap,dmpcnt,  &
     dmppnt,eotflg,ihol(22),jmp,namopt(26),pvt,seteor,sol, start,subset
 
!     NAMED COMMON AREAS /XGPIC/ AND /XGPID/ CONTAIN
!     MACHINE DEPENDENT DATA
 
!     COMMON /XGPIC / ICOLD,ISLSH,IEQUL,NBLANK,NXEQUI,
!                        ** CONTROL CARD NAMES **
!    1                NMED,NSOL,NDMAP,NESTM1,NESTM2,NEXIT,
!                        ** DMAP CARD NAMES **
!    2                NBEGIN,NEND,NJUMP,NCOND,NREPT,NTIME,NSAVE,NOUTPT,
!    3                NCHKPT,NPURGE,NEQUIV,
!      ** THE FOLLOWING CONSTANTS ARE INITIALIZED BY XGPIBS ROUTINE **
!    4                NCPW,NBPC,NWPC,
!    5                MASKLO,ISGNON,NOSGN,IALLON,MASKS(40)
 
 COMMON /xgpic / icold,iholc(21), ncpw,nbpc,nwpc,  &
     maskhi,masklo,isgnon,nosgn,iallon,masks(40)
 COMMON /xgpid / icst,iunst,imst,ihapp,idsapp,idmapp,  &
     isave,itape,iappnd,intgr,losgn, noflgs,seteor,eotflg,ieqflg,  &
     cpntry(7),jmp(7)
 
!     ****** /XGPI1 / *******
 
!     COMMON /XGPI1 / LOSCAR,OSPRC,OSBOT,OSPNT,OSCAR(1)
 
!     NOTE - /XGPI1 / MUST BE LOADED AT THE END OF LONGEST LINK IN XGPI
!                     BECAUSE IT DEFINES THE START OF OPEN CORE.
 
!     OSCAR  = OPERATION SEQUENCE CONTROL ARRAY
!     LOSCAR = LENGTH OF OSCAR ARRAY
!     OSPRC  = POINTER TO PRECEDING OSCAR ENTRY
!     OSBOT  = POINTER TO LAST OSCAR ENTRY
!     OSPNT  = POINTER TO PRESENT OSCAR ENTRY BEING PROCESSED
 
!     ***ORDER OF TABLES IN OPEN CORE DURING PHASE 1 OF COMPILATION.
!        EQUIVALENCE (OSCAR,DMPCRD,LBLTBL,MED,IBUFR)
 
!     ***ORDER OF TABLES IN OPEN CORE DURING PHASE 2 OF COMPILATION.
!        EQUIVALENCE (OSCAR,PTDIC,ICPDPL,MED,IBUFR)
!     IBUFR  = GINO BUFFER AREA LOCATED AT HIGH ADDRESS END OF OPEN
!              CORE.
!     DMPCRD = DMAP SEQUENCE CARD IMAGE BUFFER
!     PTDIC  = PROBLEM TAPE CHECKPOINT DICTIONARY
!     MED    = MODULE EXECUTION DECISION TABLE FOR RESTARTS IN RIGID
!              FORMATS
!     ICPDPL = LIST OF CHECKPOINT FILES TO BE WRITTEN ON DATA POOL FROM
!              OLD  PROBLEM TAPE IN ORDER TO RESTART PROBLEM.
!     LBLTBL = TABLE OF LABEL NAMES AND PARAMETER NAMES REFERENCED BY
!              LABEL,COND,PURGE AND EQUIV DMAP INSTRUCTIONS.
 
 COMMON /xgpi3 / pvt(200)
 COMMON /xgpi4 / irturn,insert,iseqn,dmpcnt,idmpnt,dmppnt,bcdcnt,  &
     length,icrdtp,ICHAR,newcrd,modidx,ldmap,isavdw, dmap(200)
 COMMON /xgpi5 / iapp,start,alter(2),sol,subset,iflag,  &
     iestim,icftop,icfpnt,lctlfl,ictlfl(1)
 COMMON /xgpi6 / medtp,fnmtp,cnmtp,medpnt,lmed,iplus,diag14,diag17,  &
     diag4,diag25,ifirst,ibuff(20)
 COMMON /xgpi7 / ifpnt,lfile,ifile(130)
 COMMON /xgpi8 / icptop,icpbot,lcpdpl
 COMMON /moddmp/ iflg(6),nmpt(26)
 DATA    namopt/ 4HGO  ,4H    ,4HNOGO,4H    ,4HERR ,4H    ,4HLIST,  &
     4H    ,4HNOLI,4HST  ,4HDECK,4H    ,4HNODE,4HCK  ,  &
     4HREF ,4H    ,4HNORE,4HF   ,4HOSCA,4HR   ,4HNOOS,  &
     4HCAR ,4HALL ,4H    ,4HEXCE,4HPT  /
 DATA    ihol  / 4H/   ,4H=   ,4H    ,4HXEQU,4HMED ,4HSOL ,4HDMAP,  &
4HESTI,4HM   ,4HEXIT,4HBEGI,4HEND ,4HJUMP,4HCOND,  &
    4HREPT,4HTIME,4HSAVE,4HOUTP,4HCHKP,4HPURG,4HEQUI, 4HXCHK/
DATA    ipls  / 1H+   /

!     ****** /XGPIC / *******

!     NCPW   = NUMBER OF CHARACTERS PER WORD.
!     NBPC   = NUMBER OF BITS PER CHARACTER.
!     NWPC   = NUMBER OF WORDS PER INPUT CARD (72 CHARACTERS).
!     MASKHI = MASK OUT ALL BITS EXCEPT LOW ORDER 15 BITS
!            = 2**15 - 1
!     MASKLO = MASK FOR HI ORDER 16 BITS, SIGN BIT NOT INCLUDED
!            = LSHIFT(MASKHI,16)
!     ISGNON = MASK OUT ALL BUT SIGN BIT
!            = LSHIFT(1,NBPW-1)
!     NOSGN  = MASK OUT ONLY SIGN BIT
!            = COMPLF(ISGNON)
!     IALLON = ALL BITS ON
!            = COMPLF(0)
!     MASKS  = TABLE OF MASKS FOR MASKING OUT VARIOUS CHARACTERS OF A
!              WORD. TABLE LENGTH = 4*NCPW (40 MAX.)

!     DATA     ICOLD /1     /, ISLSH /4H/   /, IEQUL /4H=   /,
!    1         NXEQUI/4HXEQU/, NMED  /4HMED /, NSOL  /4HSOL /,
!    2         NDMAP /4HDMAP/, NESTM1/4HESTI/, NESTM2/4HM   /,
!    3         NEXIT /4HEXIT/, NBEGIN/4HBEGI/, NEND  /4HEND /,
!    3         NJUMP /4HJUMP/, NCOND /4HCOND/, NBLANK/4H    /,
!    4         NREPT /4HREPT/, NTIME /4HTIME/, NSAVE /4HSAVE/,
!    5         NCHKPT/4HCHKP/, NPURGE/4HPURG/, NEQUIV/4HEQUI/,
!    6         MASKHI/32767 /, NOUTPT/4HOUTP/

icold  = 1
maskhi = 32767
!              2**15 - 1
DO  i = 1,21
  iholc(i) = ihol(i)
END DO

!     ****** /XGPID / *******

!     ICST,IUNST,IMST = COLD,UNMODIFIED,MODIFIED START CODES
!     IHAPP,IDSAPP,IDMAPP = HEAT,DISPLACEMENT,DMAP APPROACH CODES
!     ** THE FOLLOWING CONSTANTS ARE INITIALIZED IN XGPIBS ROUTINE **
!     INTGR  = INTEGER TYPE CODE RETURNED BY XSCNDM
!     ISAVE,ITAPE,IAPPND = FLAGS USED IN /XGPI7/
!     MODFLG = PARAM MODIFY FLAG IN VPS
!     LOSGN  = SIGN BIT OF LOW ORDER 16 BITS
!     NOFLGS = MASK OUT FLAGS USED IN PTDIC TABLE AND ICPDPL
!     SETEOR = END OF RECORD FLAG IN PTDIC,ICPDPL TABLES
!     EOTFLG = END OF TAPE FLAG   IN PTDIC,ICPDPL TABLES
!     IEQFLG = EQUIVALENCE FLAG   IN PTDIC,ICPDPL,DPL,FIAT TABLES
!     CPNTRY = TABLE CONTAINING HEADER SECTION OF CHECKPOINT OSCAR ENTRY
!     JMP    = TABLE CONTAINING JUMP OSCAR ENTRY TO BE INSERTED

!     DATA  ICST  /1/, IUNST/2/, IMST/3/, IDMAPP/1/, ISAVE/1/,
!    1      CPNTRY/6,2,0,4HXCHK, 4H    ,  0,0/,
!    2      JMP   /7,3,0,4HJUMP, 4H    ,  0,0/

icst   = 1
iunst  = 2
imst   = 3
idmapp = 1
isave  = 1
jmp(1) = 7
jmp(2) = 3
jmp(3) = 0
jmp(4) = ihol(13)
jmp(5) = ihol( 3)
jmp(6) = 0
jmp(7) = 0
cpntry(1) = 6
cpntry(2) = 2
cpntry(3) = 0
cpntry(4) = ihol(22)
cpntry(5) = ihol( 3)
cpntry(6) = 0
cpntry(7) = 0

!     ****** /XGPI3 / *******

!     PVT = PARAMETER VALUE TABLE
!     DATA  PVT/200,2,0,0,1,195*0/

pvt(1) = 200
pvt(2) = 2
DO  i = 3,200
  pvt(i) = 0
END DO
pvt(5) = 1

!     ****** /XGPI4 / *******

!     IRTURN = RETURN CODE USED FOR ALTERNATE RETURNS
!     INSERT = -1  INDICATES DMAP INSTRUCTION IS TO BE DELETED.
!            =  0  PROCESS DMAP INSTRUCTION FROM MAIN STREAM.
!            =  1  INSERT DMAP INSTRUCTION FROM ALTER FILE.
!     ISEQN  = NEXT OSCAR SEQUENCE NUMBER TO BE ASSIGNED.
!     DMPCNT = DMAP INSTRUCTION COUNTER
!     IDMPNT = POINTER TO NEXT ITEM TO BE SCANNED IN DMAP ARRAY
!     DMPPNT = POINTER TO ITEM IN DMAP ARRAY RETURNED BY XSCNDM ROUTINE
!     BCDCNT = NUMBER OF BCD ENTRIES REMAINING IN DMAP ARRAY BEFORE MODE
!              CHANGES.
!     LENGTH = LENGTH (IN WORDS) OF BINARY VALUE RETURNED BY XSCNDM
!              ROUTINE.
!     ICRDTP = POINTER TO NEXT WORD TO BE PROCESSED IN DMPCRD ARRAY.
!     ICHAR  = POINTER TO NEXT CHARACTER TO BE PROCESSED IN DMPCRD ARRAY
!     NEWCRD = FLAG TO INDICATE WHETHER OR NOT TO PREPARE NEXT CARD
!              IMAGE FOR TRANSLATION BY XRCARD ROUTINE.
!     MODIDX = MODULE INDEX STORED IN OSCAR ENTRY FOR USE BY XSEM
!              ROUTINE.
!     LDMAP  = LENGTH OF DMAP ARRAY.
!     ISAVDW = POINTER TO LAST DELIMITER ENCOUNTERED IN DMPCRD ARRAY,
!              USED BY XSCNDM WHEN UNPACKING RIGID FORMAT DMAP SEQUENCE.
!     DMAP   = ARRAY CONTAINING OUTPUT FROM XRCARD ROUTINE.

!     DESCRIPTION OF VARIABLES EQUIVALENCED TO /XGPI4/ ENTRIES
!     EQUIVALENCE (DMAP,ICF)
!     ICF    = TEMPORARY STORAGE FOR CONTROL FILE DICTIONARY.

!     DATA     ISEQN/1/, DMPCNT/0/, ICHAR/1/, LDMAP/200/, BCDCNT/0/

iseqn  = 1
dmpcnt = 0
ICHAR  = 1
ldmap  = 200
bcdcnt = 0

!     ****** /XGPI5/ *******

!     IAPP   = APPROACH CODE.
!     START  = TYPE OF START CODE.
!     ALTER  = DMAP NOS. OF INSTRUCTIONS TO BE ALTERED
!     SOL    = SOLUTION CODE.
!     SUBSET = SOLUTION SUBSET CODE.
!     IFLAG  = FLAG FOR USE IN SUBROUTINE XLNKHD.
!     IESTIM = POINTER TO ESTIM ENTRIES IN ICTLFL OR ZERO.
!     ICFTOP = POINTER TO FIRST WORD IN ICTLFL ARRAY
!     ICFPNT = POINTER TO NEXT AVAILABLE WORD IN ICTLFL ARRAY
!     LCTLFL = LENGTH OF ICTLFL ARRAY.
!     ICTLFL = ARRAY CONTAINING INFORMATION FROM ESTIM CONTROL CARD.

!     DATA     IESTIM/0/, ICFTOP/1/, LCTLFL/1/, IFLAG/0/

iestim = 0
icftop = 1
lctlfl = 1
iflag  = 0

!     ****** /XGPI6/ *******

!     MED    = (SEE DESCRIPTION IN /XGPI1/)
!     MEDTP  = POINTER TO FIRST WORD IN MED ARRAY.
!     LMED   = LENGTH OF MED ARRAY.
!     MEDPNT = POINTER TO AN ENTRY IN MED
!     FNMTP  = POINTER TO FIRST WORD OF FILE NAME PORTION OF MED TABLE
!     CNMTP  = POINTER TO FIRST WORD OF CARD NAME PORTION OF MED TABLE
!     IPLUS  = PLUS CHARACTER FOR PRINTER SPACE SUPRESS
!     DIAG14 = SKIP DMAP PRINT UNLESS RESTART (SET BY XGPI)
!     DIAG17 = DMAP PUNCH OPTION FLAG (SET BY XGPI)

!     DATA     MEDTP/1/,  LMED/0/,  IPLUS/1H+/

medtp  = 1
lmed   = 0
iplus  = ipls

!     ****** /XGPI7/ *******

!     IFPNT  = POINTER TO LAST ENTRY IN FILE TABLE
!     LFILE  = LENGTH OF FILE TABLE (IN WORDS)
!     IFILE  = TABLE CONTAINING INFO FROM FILE DMAP INSTRUCTION

!     DATA     IFPNT/-2/,  LFILE/130/,  IFILE/130*0/

ifpnt  = -2
lfile  = 130
DO  i = 1,lfile
  ifile(i) = 0
END DO

!     ****** /XGPI8 / *******

!     ICPDPL = (SEE /XGPI1/ FOR DESCRIPTION)
!     ICPTOP = POINTER TO FIRST ENTRY IN ICPDPL ARRAY.
!     ICPBOT = POINTER TO LAST  ENTRY IN ICPDPL ARRAY.
!     LCPDPL = LENGTH OF ICPDPL ARRAY)

!     DATA     ICPTOP/0/,  ICPBOT/0/,  LCPDPL/0/

icptop = 0
icpbot = 0
lcpdpl = 0

!     ****** /MODDMP/ ********

iflg(1) = 1
iflg(2) = 2
iflg(3) = 0
iflg(4) = 0
iflg(5) = 0
iflg(6) = 0
DO  i = 1,26
  nmpt(i) = namopt(i)
END DO

RETURN
END SUBROUTINE xgpidd
